# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Picashare' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Picashare

  # Required by RNFirebase
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/AppIndexing'
  pod 'Firebase/Core'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'Google/SignIn'
  pod 'Fabric'
  pod 'TwitterKit'
  pod 'TwitterCore'
end

target 'Picashare-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Picashare-tvOS

  target 'Picashare-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
